geyser_data_original = [
"[GR|PC] Find The Cell On The Path",
"[GR|PC] Open The Precursor Door",
"[GR|PC] Climb Up The Cliff",
"[GR|PC] Free 7 Scout Flies",
"[GR|SF] On Ground (Near Cell)",
"[GR|SF] On Ground (Far From Cell)",
"[GR|SF] On Left Ledge",
"[GR|SF] On Right Ledge",
"[GR|SF] On Middle Ledge (Left)",
"[GR|SF] On Middle Ledge (Right)",
"[GR|SF] On Top Ledge",
"[GR|MISC] Open The Locked Precursor Door"
]

data_original = [
"[SV|PC] Bring 90 Orbs To The Mayor",
"[SV|PC] Bring 90 Orbs To Your Uncle",
"[SV|PC] Herd The Yakows Into Their Pen",
"[SV|PC] Bring 120 Orbs To The Oracle",
"[SV|PC] Bring 120 Orbs To The Oracle",
"[SV|PC] Free 7 Scout Flies",
"[SB|PC] Unblock The Eco Harvesters",
"[SB|PC] Push The Flut Flut Egg Off The Cliff",
"[SB|PC] Get The Power Cell From The Pelican",
"[SB|PC] Chase The Seagulls",
"[SB|PC] Launch Up To The Cannon Tower",
"[SB|PC] Explore The Beach",
"[SB|PC] Climb The Sentinel",
"[SB|PC] Free 7 Scout Flies",
"[FJ|PC] Connect The Eco Beams",
"[FJ|PC] Get To The Top Of The Temple",
"[FJ|PC] Find The Blue Vent Switch",
"[FJ|PC] Defeat The Dark Eco Plant",
"[FJ|PC] Catch 200 Pounds Of Fish",
"[FJ|PC] Follow The Canyon To The Sea",
"[FJ|PC] Open The Locked Temple Door",
"[FJ|PC] Free 7 Scout Flies",
"[MI|PC] Catch The Sculptor's Muse",
"[MI|PC] Climb The Lurker Ship",
"[MI|PC] Stop The Cannon",
"[MI|PC] Return To The Dark Eco Pool",
"[MI|PC] Destroy The Balloon Lurkers",
"[MI|PC] Use The Zoomer To Reach Power Cell",
"[MI|PC] Use Blue Eco To Reach Power Cell",
"[MI|PC] Free 7 Scout Flies",
"[SV|SF] In Fisherman's House",
"[SV|SF] In Mayor's House",
"[SV|SF] In Farmer's House",
"[SV|SF] Near Oracle",
"[SV|SF] Under Bridge",
"[SV|SF] Behind Sculptor's House",
"[SV|SF] Overlooking Farmer's House",
"[FJ|SF] At End Of Path",
"[FJ|SF] On Spiral Of Stumps",
"[FJ|SF] Behind Lurker Machine",
"[FJ|SF] At End Of River",
"[FJ|SF] Around Temple Spire",
"[FJ|SF] On Top Of Temple",
"[FJ|SF] Near Dark Eco Boxes",
"[MI|SF] Overlooking Entrance",
"[MI|SF] On Zoomer Ramps",
"[MI|SF] On Ledge Near Arena Exit",
"[MI|SF] On Ledge Near Arena Entrance",
"[MI|SF] Near Arena Door",
"[MI|SF] On Ship",
"[MI|SF] On Barrel Ramps",
"[SB|SF] At Entrance",
"[SB|SF] Overlooking Locked Boxes",
"[SB|SF] On Path To Flut Flut",
"[SB|SF] Under Wood Pillars",
"[SB|SF] On Sentinel",
"[SB|SF] Overlooking Blue Eco Vent",
"[SB|SF] Overlooking Green Eco Vents",
"[GR|MISC] Open The Locked Precursor Door",
"[SV|MISC] Yakow Near Village",
"[SV|MISC] Yakow Near Fields",
"[SV|MISC] Yakow Near Water (Close)",
"[SV|MISC] Yakow Near Water (Far)",
"[SV|MISC] Yakow Near Forbidden Jungle",
"[FJ|MISC] Destroy Mirror",
"[FJ|MISC] Construct Bridge To Temple",
"[FJ|MISC] Connect A Mirror",
"[FJ|MISC] Connect A Mirror",
"[FJ|MISC] Connect A Mirror",
"[FJ|MISC] Connect A Mirror",
"[FJ|MISC] Connect A Mirror",
"[FJ|MISC] Beat Plant Boss",
"[FJ|MISC] Open Locked Temple Door",
"[SB|MISC] Stop The Shooting Cannon",
"[SB|MISC] Chase Seagulls 1st Time",
"[SB|MISC] Chase Seagulls 2nd Time",
"[SB|MISC] Chase Seagulls 3rd Time",
"[SB|MISC] Push Flut Flut Egg",
"[SB|MISC] Harvester On Ground Level",
"[SB|MISC] Harvester On 1st Level",
"[SB|MISC] Harvester On 2nd Level",
"[SB|MISC] Harvester On 3rd Level",
"[SB|MISC] Harvester On 4th Level",
"[MI|MISC] Stop The Shooting Cannon",
"[MI|MISC] Catch Muse",
"[MI|MISC] Defeat The Ambush",
"[MI|MISC] Stop The Balloon Lurkers", #before fcs
"[FC|PC] Free 7 Scout Flies",
"[FC|PC] Reach The End Of Fire Canyon",
"[FC|PC] Reach The End Of Fire Canyon",
"[FC|PC] Reach The End Of Fire Canyon",
"[FC|PC] Reach The End Of Fire Canyon",
"[FC|PC] Reach The End Of Fire Canyon",
"[FC|SF] 1st Scout Fly",
"[FC|SF] 2nd Scout Fly",
"[FC|SF] 3rd Scout Fly",
"[FC|SF] 4th Scout Fly",
"[FC|SF] 5th Scout Fly",
"[FC|SF] 6th Scout Fly",
"[FC|SF] 7th Scout Fly", #after fcs
"[RV|PC] Bring 90 Orbs To The Gambler",
"[RV|PC] Bring 90 Orbs To The Geologist",
"[RV|PC] Bring 90 Orbs To The Warrior",
"[RV|PC] Bring 120 Orbs To The Oracle",
"[RV|PC] Bring 120 Orbs To The Oracle",
"[RV|PC] Free 7 Scout Flies",
"[LPC|PC] Raise The Chamber",
"[LPC|PC] Follow The Coloured Pipes",
"[LPC|PC] Reach The Bottom Of The City",
"[LPC|PC] Quickly Cross The Dangerous Pool",
"[LPC|PC] Match The Platform Colours",
"[LPC|PC] Climb The Slide Tube",
"[LPC|PC] Reach The Center Of The Complex",
"[LPC|PC] Free 7 Scout Flies",
"[BS|PC] Ride The Flut Flut",
"[BS|PC] Protect Farthy's Snacks",
"[BS|PC] Deafeat The Lurker Ambush",
"[BS|PC] Break The 1st Tether On The Zeppelin",
"[BS|PC] Break The 2nd Tether On The Zeppelin",
"[BS|PC] Break The 3rd Tether On The Zeppelin",
"[BS|PC] Break The 4th Tether On The Zeppelin",
"[BS|PC] Free 7 Scout Flies",
"[PB|PC] Herd The Moles Into Their Hole",
"[PB|PC] Catch The Flying Lurkers",
"[PB|PC] Beat The Record Time On The Gorge",
"[PB|PC] Get The Power Cell Over The Lake",
"[PB|PC] Cure Dark Eco Infected Plants",
"[PB|PC] Navigate The Purple Precursor Rings",
"[PB|PC] Navigate The Blue Precursor Rings",
"[PB|PC] Free 7 Scout Flies",
"[RV|SF] Behind Sage's Hut",
"[RV|SF] Near Waterfall",
"[RV|SF] Behind Geologist",
"[RV|SF] Behind Fiery Boulder",
"[RV|SF] On Dock",
"[RV|SF] At Boggy Swamp Entrance",
"[RV|SF] At Pontoon Bridge",
"[PB|SF] At Purple Ring Start",
"[PB|SF] Overlooking Entrance",
"[PB|SF] At Blue Ring Start",
"[PB|SF] Before Big Jump",
"[PB|SF] Near Dark Eco Plant (Below)",
"[PB|SF] Near Dark Eco Plant (Above)",
"[PB|SF] Near Mole Hole",
"[LPC|SF] First Room",
"[LPC|SF] Before Second Room",
"[LPC|SF] Second Room Near Orb Vent",
"[LPC|SF] Second Room (Green Pipe)",
"[LPC|SF] Second Room (Blue Pipe)",
"[LPC|SF] Second Room On Path To Cell",
"[LPC|SF] Across Steam Vents",
"[BS|SF] Near Entrance",
"[BS|SF] Over First Jump Pad",
"[BS|SF] Over Second Jump Pad",
"[BS|SF] Across Black Swamp",
"[BS|SF] Overlooking Flut Flut",
"[BS|SF] On Flut Flut Platforms",
"[BS|SF] In Field Of Boxes",
"[RV|MISC] Press The Blue Warp Gate Button",
"[PB|MISC] Flying Lurker Near Plants",
"[PB|MISC] Flying Lurker Near Pillars",
"[PB|MISC] Flying Lurker Near Purple Rings",
"[PB|MISC] Flying Lurker Near Entrance",
"[PB|MISC] Herd A Mole",
"[PB|MISC] Herd A Mole",
"[PB|MISC] Herd A Mole",
"[PB|MISC] Herd A Mole",
"[PB|MISC] Cure The Plants",
"[PB|MISC] Beat The Purple Rings",
"[PB|MISC] Beat The Blue Rings",
"[PB|MISC] Beat The Record Time",
"[LPC|MISC] Open The Sunken Chamber",
"[BS|MISC] Shoot 1st Boulder",
"[BS|MISC] Shoot 2nd Boulder",
"[BS|MISC] Shoot 3rd Boulder",
"[BS|MISC] Shoot 4th Boulder",
"[BS|MISC] Shoot Boulder Blocking Jump Pad",
"[BS|MISC] Defeat Ambush", #before boulder skip
"[RV|MISC] Lift Boulder",
"[RV|MISC] Lift Boulder",
"[RV|MISC] Lift Boulder",
"[RV|MISC] Lift Boulder",
"[RV|MISC] Lift Boulder",
"[MP|PC] Defeat Klaww",
"[MP|PC] Find The Hidden Power Cell",
"[MP|PC] Free 7 Scout Flies",
"[MP|SF] 1st Scout Fly",
"[MP|SF] 2nd Scout Fly",
"[MP|SF] 3rd Scout Fly",
"[MP|SF] 4th Scout Fly",
"[MP|SF] 5th Scout Fly",
"[MP|SF] 6th Scout Fly",
"[MP|SF] 7th Scout Fly",
"[MP|MISC] Stop Klaww",
"[MP|MISC] Stop Klaww",
"[MP|MISC] Stop Klaww",
"[MP|MISC] Stop Klaww",
"[MP|MISC] Stop Klaww",
"[MP|MISC] Stop The Bomb Lurker",
"[MP|MISC] Stop The Bomb Lurker",
"[MP|MISC] Stop The Bomb Lurker",
"[MP|MISC] Stop The Bomb Lurker",
"[MP|MISC] Stop The Bomb Lurker", #bomb lurker softlock
"[MP|PC] Reach The End Of The Mountain Pass",
"[VC|PC] Bring 90 Orbs To The Miners",
"[VC|PC] Bring 90 Orbs To The Miners",
"[VC|PC] Bring 90 Orbs To The Miners",
"[VC|PC] Bring 90 Orbs To The Miners",
"[VC|PC] Bring 120 Orbs To The Oracle",
"[VC|PC] Bring 120 Orbs To The Oracle",
"[VC|PC] Find The Hidden Power Cell",
"[VC|PC] Free 7 Scout Flies",
"[SC|PC] Shoot The Gnawing Lurkers",
"[SC|PC] Destroy The Dark Eco Crystals",
"[SC|PC] Explore The Dark Cave",
"[SC|PC] Climb The Giant Robot",
"[SC|PC] Launch To The Poles",
"[SC|PC] Navigate The Spider Tunnel",
"[SC|PC] Climb The Precursor Platforms",
"[SC|PC] Free 7 Scout Flies",
"[SM|PC] Find The Yellow Vent Switch",
"[SM|PC] Stop The 3 Lurker Glacier Troops",
"[SM|PC] Deactivate The Precursor Blockers",
"[SM|PC] Open The Frozen Crate",
"[SM|PC] Get Through The Lurker Fort",
"[SM|PC] Open The Lurker Fort Gate",
"[SM|PC] Survive The Lurker-Infested Cave",
"[SM|PC] Free 7 Scout Flies",
"[VC|SF] Near Mountain Pass",
"[VC|SF] In Miner's Cave",
"[VC|SF] Near Oracle",
"[VC|SF] On Stone Platforms",
"[VC|SF] Near Lava Tube",
"[VC|SF] At Minecart Junction",
"[VC|SF] Near Spider Cave",
"[SC|SF] Main Cave Overlooking Entrance",
"[SC|SF] Main Cave Near Robot Cave Entrance",
"[SC|SF] Near Dark Cave Entrance",
"[SC|SF] In Dark Cave",
"[SC|SF] Main Cave Near Dark Crystal",
"[SC|SF] Robot Cave (Bottom Level)",
"[SC|SF] Robot Cave (Top Level)",
"[SM|SF] Near Entrance",
"[SM|SF] Under Bridge To Fort",
"[SM|SF] On Cliff Near Flut Flut",
"[SM|SF] Near Yellow Eco Switch",
"[SM|SF] Near Frozen Box",
"[SM|SF] On Top Of Fort Tower",
"[SM|SF] On Top Of Fort",
"[VC|MISC] Press The Red Warp Gate Button",
"[VC|MISC] Destroy The Hidden Crate",
"[SC|MISC] Lurker On Ground Near Entrance",
"[SC|MISC] Lurker On Ground On Island",
"[SC|MISC] Lurker On Ground Across Eco River",
"[SC|MISC] Lurker On 2nd Level Near Dark Cave",
"[SC|MISC] Lurker On 2nd Level To Left (Lower)",
"[SC|MISC] Lurker On 2nd Level To Left (Upper)",
"[SC|MISC] Lurker On 2nd Level To Right",
"[SC|MISC] Lurker On Wooden Platform (Lower)",
"[SC|MISC] Lurker On Wooden Platform (Upper)",
"[SC|MISC] Crystal In Dark Cave",
"[SC|MISC] Crystal Near Robot Room",
"[SC|MISC] Crystal Under The Ceiling",
"[SC|MISC] Crystal Near Dark Cave (In Water)",
"[SC|MISC] Crystal Near Dark Cave (On Ledge)",
"[SM|MISC] Destroy Frozen Crate",
"[SM|MISC] Activate The Fort Elevator",
"[SM|MISC] Glacier Troop Near Flut Flut",
"[SM|MISC] Glacier Troop Near Snow Balls",
"[SM|MISC] Glacier Troop In Cave",
"[SM|MISC] Blocker Near Gondola",
"[SM|MISC] Blocker Near Snow Balls (Left)",
"[SM|MISC] Blocker Near Snow Balls (Right)",
"[SM|MISC] Blocker Near Hidden Entrance",
"[SM|MISC] Blocker In Lurker Cave",
"[SM|MISC] Blocker Near Bridge To Lurker Cave",
"[SM|MISC] Blocker On Platform To Lurker Cave (Left)",
"[SM|MISC] Blocker On Platform To Lurker Cave (Right)",
"[SM|MISC] Blocker Near First Bridge (To The Left)",
"[SM|MISC] Blocker Above Switch On Ice",
"[SM|MISC] Blocker Above Switch Near Slide",
"[SM|MISC] Blocker Above Switch Near Metal Boxes",
"[SM|MISC] Blocker Above Switch Across Eco Vent", #before lts
"[LT|PC] Reach The End Of The Lava Tube",
"[LT|PC] Reach The End Of The Lava Tube",
"[LT|PC] Reach The End Of The Lava Tube",
"[LT|PC] Reach The End Of The Lava Tube",
"[LT|PC] Reach The End Of The Lava Tube",
"[LT|PC] Free 7 Scout Flies",
"[C|PC] Free The Yellow Sage",
"[C|PC] Free The Red Sage",
"[C|PC] Free The Blue Sage",
"[C|PC] Free The Green Sage",
"[C|PC] Free 7 Scout Flies",
"[LT|SF] 1st Scout Fly",
"[LT|SF] 2nd Scout Fly",
"[LT|SF] 3rd Scout Fly",
"[LT|SF] 4th Scout Fly",
"[LT|SF] 5th Scout Fly",
"[LT|SF] 6th Scout Fly",
"[LT|SF] 7th Scout Fly",
"[C|SF] At Entrance",
"[C|SF] Before Jumping Lurkers",
"[C|SF] Main Room Left Of Robot",
"[C|SF] At Launch Pad Room",
"[C|SF] At Blast Furnace",
"[C|SF] Main Room Right Of Robot",
"[C|SF] Top Of Rotating Tower",
"[LT|MISC] Destroy Oranges",
"[LT|MISC] Destroy Oranges",
"[LT|MISC] Destroy Oranges",
"[LT|MISC] Destroy Oranges",
"[LT|MISC] Destroy Oranges",
"[LT|MISC] Press Citadel Warp Gate Button",
"[C|MISC] Destroy Jumping Lurker Spawners"
]